<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>AssessmentValidation</name>
  <uuid>116e6573-95c4-4409-9671-0c781980e1b3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	the number of years between the currentDate of DateInput and the dateOfBirth of AssessmentController > 18
    and the status of AssessmentController is ACTIVE 
    and the firstTreatmentDate is before the currentDate 
    and the firstTreatmentDate is before the currentDate of DateInput
then 
	set decision to { a new AssessmentResponse where 
	the dueDate is the nextEstimatedAppointment of DateInput } ;
else  
	set decision to an empty list of AssessmentResponses ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
